spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #- id: backend-service
        #  uri: lb:http://BACKEND-SERVICE
        #  predicates:
        #    - Path=/api/v1/backend/**
        - id: backend-service
          uri: lb:http://BACKEND-SERVICE
          predicates:
            - Path=/api/v1/**
server:
  port: 8080
